### ISSUE TITLE
ReferenceError: Unknown plugin "syntax-dynamic-import"

### ISSUE THREAD

**Issue by hazemalabiad** [felixHerder/testing-workshop-fem#1]
Environment info:

* `node` version (`node --version`): v16.14.0 
* `npm` version (`npm --version`): v8.3.1
* `yarn` version (`yarn --version`): v1.22.17

Problem description:

To start the first exercise of the workshop `other/simple-react/__tests__/item-list.todo.js` I need to run `yarn test:react` then, immediately I am getting this error:
```ts
 FAIL   react  other/simple-react/__tests__/item-list.todo.js
  ● Test suite failed to run

    ReferenceError: Unknown plugin "syntax-dynamic-import" specified in "/root/ws/testing-workshop-fem/other/configuration/calculator.solution/.babelrc.js" at 0, attempted to resolve relative to "/root/ws/testing-workshop-fem/other/configuration/calculator.solution" (While processing preset: "/root/ws/testing-workshop-fem/other/configuration/calculator.solution/.babelrc.js")
      
      at ../../node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
          at Array.map (<anonymous>)
      at Function.normalisePlugins (../../node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
      at OptionManager.mergeOptions (../../node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
      at ../../node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
      at ../../node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
          at Array.map (<anonymous>)
      at OptionManager.resolvePresets (../../node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
      at OptionManager.mergePresets (../../node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
      at OptionManager.mergeOptions (../../node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
```

Suggested solution:
- I guess it is something to do with the able & babel plugin `syntax-dynamic-import` however, I have no experience in working with this kind of tool.

**Comment by felixHerder** [comment]
When first installing use:  npm install --legacy-peer-deps  or the yarn equivalent. 
Also I'd recommend cloning Ken's original repo: https://github.com/kentcdodds/testing-workshop . This is just my personal back-up.
